version: '3'
services:
  zilla:
    image: ghcr.io/aklivity/zilla:latest
    container_name: zilla
    environment:
      AIVEN_SERVER_HOSTNAME: zilla-kafka-devrel-ben.aivencloud.com
      AIVEN_SERVER_PORT: 15545
      TRUSTORE_PASSWORD: AivenZilla
      KEYSTORE_PASSWORD: AivenZilla
      TRUST_CERT_ALIAS: Aiven_Client_Cert
      KEY_CERT_ALIAS: Aiven_CA_Cert
      JAVA_OPTS: "-Djavax.net.debug=all"
    ports:
      - "8080:8080"
    volumes:
      - ./zilla.yaml:/etc/zilla/zilla.yaml
      - ./certs/:/etc/zilla/certs
      - ./index.html:/var/www/index.html
    command: start -v -e

networks:
  default:
    name: zilla-network
    driver: bridge

